all:
	pdflatex main/report.tex

edit:
	gedit \
	main/report.tex \
	chapters/00preface.tex \
	chapters/01introduction.tex \
	chapters/02theory.tex \
	chapters/03model.tex \
	chapters/04result.tex \
	chapters/05conclusion.tex \
	chapters/06reference.tex \
	chapters/07appendix.tex
