all:
	pdflatex report.tex

edit:
	geany -i \
	report.tex \
	s00-preface/preface.tex \
	s01-introduction/introduction.tex \
	s02-theory/theory.tex \
	s03-model/model.tex \
	s04-result/result.tex \
	s05-conclusion/conclusion.tex \
	s06-reference/reference.tex \
	s07-appendix/appendix.tex
