all:
	pdflatex main
	bibtex main
	pdflatex main
	pdflatex main

edit:
	geany -i \
	main.tex \
	sections/01abstract.tex \
	sections/02introduction.tex \
	sections/03theory.tex \
	sections/04model.tex \
	sections/05result.tex \
	sections/06conclusion.tex \
	sections/07reference.bib \
