all:
	pdflatex shabbir_2D-network-porous-media_article
	bibtex shabbir_2D-network-porous-media_article
	pdflatex shabbir_2D-network-porous-media_article
	bibtex shabbir_2D-network-porous-media_article
	pdflatex shabbir_2D-network-porous-media_article
	clear
	pdflatex shabbir_2D-network-porous-media_article
